name: Retrain WorkFlow

on:
  pull_request:
    branches: ['main']

permissions: write-all

jobs:
  retrain_and_reporting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Intall dependencies
        run: pip install -r requirements.txt

      - name: Install own modules
        run: pip install -e .

      - name: Pull data
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID2}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRECT_KEY2}}
        run: |
          dvc pull -r my_s3
        
      - name: Run dvc pipeline
        run: dvc repro

      - name: Write Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           echo '# Retail TimeSeries Forescast Report' >> report.md
           cat metrics.json
           set +H
           echo "![Historical Forescast /  Backtest](backtest_plot.png)" >> report.md
           echo "![Error (RMSE) distribution plot](error_dist_plot.png)" >> report.md
           cml comment create model_eval_report.md
           set -H

  
