name: Test and Retrain

on:
  pull_request:
    branches: ['main']

permissions: write-all

jobs:
  retrain_and_reporting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Intall dependencies
        run: pip install -r requirements.txt

      - name: Install own modules
        run: pip install -e .

      - name: Pull data
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID2}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRECT_KEY2}}
        run: |
          dvc pull -r my_s3
        
      - name: Run dvc pipeline
        env:
          MLFLOW_TRACKING_PASSWORD: ${{secrets.DAGSHUB_TOKEN}}
          DAGSHUB_USER_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
          DAGSHUB_CLIENT_TOKENS_CACHE: ${{secrets.DAGSHUB_TOKEN}}
        run: dvc repro

      - name: Run unit tests
        run: python3 tests/data_test.py

      - name: Checks images
        run: ls -la

      - name: Write Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           echo '# Retail TimeSeries Forescast Report' >> report.md
           dvc metrics show >> report.md
           echo '## Historical Forecast' >> report.md
           dvc plots show backtest_plot.png >> report.md
           cml publish --md ../backtest_plot.png >> report.md
           echo '## Error Distribution' >> report.md
           dvc plots show error_dist_plot.png >> report.md
           echo '## Testing Forecasting' >> report.md
           dvc plots show testing_plot.png >> report.md
           cml comment create report.md

      - name: Update data tracking
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID2}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRECT_KEY2}}
        run: |
          dvc add data/raw/features_data_set.csv
          dvc add data/raw/sales_data_set.csv
          dvc add data/raw/stores_data_set.csv
          dvc commit 
          dvc push -r my_s3
  
